language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
script:
- mvn clean install
after_script:
- build=$(grep "Open Liberty" target/liberty/wlp/usr/servers/defaultServer/logs/console.log
  | cut -d' ' -f5 | cut -d')' -f1 ); release=$( echo "$build" | cut -d'/' -f1); number=$(
  echo "$build" | cut -d'/' -f2); ol_jv=$(grep -i "on java" target/liberty/wlp/usr/servers/defaultServer/logs/console.log);
  jv=$(printf '%s\n' "${ol_jv//$' on '/$'\n'}" | sed '2q;d'); echo -e "\n"; echo -e  "\033[1;34mOpen
  Liberty release:\033[0m \033[1;36m$release\033[0m"; echo -e "\033[1;34mOpen Liberty
  build number:\033[0m \033[1;36m$number\033[0m"; echo -e "\033[1;34mJava version:\033[0m
  \033[1;36m$jv\033[0m";
- cd target/liberty/wlp/usr/servers/defaultServer/logs/; repo_name=$(echo "$TRAVIS_REPO_SLUG"
  | sed -e "s/\//-/g"); if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then result="passed";
  else result="failed"; fi; serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$result.zip";zip
  -r "$serverlogsarchive" .; curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/";
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: JRd5BRPlWxcp5Nx8a/F73QsDN0yEw58VSwkTtupbfuLpyV6u0Hw/oEbF5xsH4ejTAdzpzrqbA21Yti05/GlFPMU7aTyGZAvVLPtBn09Dixxu+/6IxE/8h+uWYlszFs2tpXqL6aICw3JCfHJGBAzp926TNdX5ITsSXGbQGFaa4FreW/NFYIidCGnwm2N+5QH4oGzgvGL0PeNPQsj1Br42cxpyTJTYHei1eoD2m4/tbP/ZBW41ZanuLGA+btpgCoyUweqQ8vHX/Ia4tQdtEIWZ9BtdeTnzUiGRTxL4N0SFnNDO70dm9YGYwBGY+ZQb66hj88JUvCKNgraQuI49bsY4tIkABwo+Eq8T7TWE5HnKMQE70rnvrSSLTeuZE0ZVtH07WscblrkW/gF2fHUDRNnoeAQodRNtx6hDr7CwWlYof7/duozE+VbL2zs9ajwDg0L4Tpm2JJArdB9QG7bHH9F5/Ls8gMpxaipZjafCeNbxyzfycgOaQSxi/giSYbXeSV8ZaW4XW440DKaHDY9loHdfUlkrh0WJkxnCuGlsWHX6ZtUfrSaxTXQkHO7rHR0ThFw2ll9f+IMJDblZaN1bUd5QrqO94tMOA56GbajaU0aP7a1SBbfVSqDTfnD6T03k6nwxhMSmTWWQL+iG2kqji907BPJpluRS4CgkcgyxcwiDICs=
    on_success: never
    on_failure: always
branches:
  only:
  - master
